module.exports = {
  ADD_USER_FROM_CLIENT: 'ADD_USER_FROM_CLIENT',
  ADD_USER_FROM_SERVER: 'ADD_USER_FROM_SERVER',

  ADD_CHAT_FROM_CLIENT: 'ADD_CHAT_FROM_CLIENT',
  ADD_CHAT_FROM_SERVER: 'ADD_CHAT_FROM_SERVER',

  ADD_FRIEND_FROM_CLIENT: 'ADD_FRIEND_FROM_CLIENT',
  ADD_FRIEND_FROM_SERVER: 'ADD_FRIEND_FROM_SERVER',

  USER_LEAVE_FROM_SERVER: 'USER_LEAVE_FROM_SERVER',

  DELETE_CHAT_FROM_CLIENT: 'DELETE_CHAT_FROM_CLIENT',
  DELETE_CHAT_FROM_SERVER: 'DELETE_CHAT_FROM_SERVER',

  ADD_MESSAGE_FROM_CLIENT: 'ADD_MESSAGE_FROM_CLIENT',
  ADD_MESSAGE_FROM_SERVER: 'ADD_MESSAGE_FROM_SERVER',
}