module.exports = {
  ADD_USER_FROM_CLIENT: 'ADD_USER_FROM_CLIENT',
  ADD_USER_FROM_SERVER: 'ADD_USER_FROM_SERVER',
  ADD_MESSAGE_FROM_CLIENT: 'ADD_MESSAGE_FROM_CLIENT',
  ADD_MESSAGE_FROM_SERVER: 'ADD_MESSAGE_FROM_SERVER',
}